import { ICard } from "../types";

export const HEADER_ITEMS: {
  link: string;
  label: string;
  isActive: boolean;
  isBig?: boolean;
}[] = [
  {
    link: "/",
    label: "home",
    isActive: true,
  },
  {
    link: "summon",
    label: "summon",
    isActive: true,
  },
  {
    link: "card-desk",
    label: "card desk",
    isActive: true,
  },
  {
    link: "battle",
    label: "battle",
    isActive: true,
    isBig: true,
  },
  {
    link: "world",
    label: "world",
    isActive: false,
  },
  {
    link: "mini-games",
    label: "mini games",
    isActive: false,
  },
  {
    link: "contact",
    label: "contact",
    isActive: true,
  },
];

export const CARD_TYPES: {
  id: number;
  label: string;
}[] = [
  {
    id: 0,
    label: "blade",
  },
  {
    id: 1,
    label: "decade",
  },
  {
    id: 2,
    label: "kabuto",
  },
  {
    id: 3,
    label: "zio",
  },
  {
    id: 4,
    label: "ryuki",
  },
  {
    id: 5,
    label: "zero one",
  },
  {
    id: 6,
    label: "dragonball z",
  },
  {
    id: 7,
    label: "naruto",
  },
];

export const CARDS: ICard[] = [
  {
    frontPath: "/images/zeroone_front.webp",
    thumbnail: "/characters/zero_one/zeroone.svg",
    name: "Zero-One",
    star: 4,
    sound: "/sounds/zero_one.MP3",
    type: 5,
  },
  {
    frontPath: "/images/decade_front.webp",
    thumbnail: "/characters/decade/decade.svg",
    name: "Decade",
    star: 5,
    sound: "/sounds/decade.mp3",
    type: 1,
  },
  {
    frontPath: "/images/zio_front.webp",
    thumbnail: "/characters/zio/zio.svg",
    name: "Zio",
    star: 4,
    sound: "/sounds/zio.mp3",
    type: 3,
  },
  {
    frontPath: "/images/decade_front.webp",
    thumbnail: "/characters/decade/KRDCD-Decadecompletejumboformation.svg",
    name: "Decade Complete Form",
    star: 6,
    sound: "/sounds/decade_complete.mp3",
    type: 1,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/Blade_AceForm.svg",
    name: "Blade",
    star: 4,
    sound: "/sounds/blade.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Blade_JackForm.svg",
    name: "Blade Jack Form",
    star: 5,
    sound: "/sounds/blade_jack.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Blade_KingForm.svg",
    name: "Blade King Form",
    star: 6,
    sound: "/sounds/garren_king.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Chalice_AceForm.svg",
    name: "Chalice",
    star: 4,
    sound: "/sounds/chalice.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Wild_Chalice.svg",
    name: "Chalice Wild Form",
    star: 6,
    sound: "/sounds/chalice_wild.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Chalice_Joker.svg",
    name: "Chalice Joker Form",
    star: 5,
    sound: "/sounds/chalice_joker.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-AlbinoJoker.svg",
    name: "Chalice Albino Joker Form",
    star: 5,
    sound: "/sounds/chalice_joker.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Garren_AceForm.svg",
    name: "Garren",
    star: 4,
    sound: "/sounds/garren.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Garren_JackForm.svg",
    name: "garren jack form",
    star: 5,
    sound: "/sounds/garren_jack.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KRBl-Garrenking.svg",
    name: "Garren King Form",
    star: 6,
    sound: "/sounds/garren_king.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KR-Leangle.svg",
    name: "Leangle",
    star: 4,
    sound: "/sounds/leangle.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KRBl-Leanglejack.svg",
    name: "leangle jack form",
    star: 5,
    sound: "/sounds/leangle_jack.mp3",
    type: 0,
  },
  {
    frontPath: "/images/blade_front.webp",
    thumbnail: "/characters/blade/KRBl-Leangleking.svg",
    name: "leangle King Form",
    star: 6,
    sound: "/sounds/leangle_king.mp3",
    type: 0,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/KABUTO-MASKED.svg",
    name: "Kabuto masked form",
    star: 3,
    sound: "/sounds/kabuto.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/KABUTO-RIDER.svg",
    name: "Kabuto",
    star: 4,
    sound: "/sounds/kabuto_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/DARK-KABUTO-RIDER.svg",
    name: "Dark Kabuto",
    star: 4,
    sound: "/sounds/kabuto_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/KABUTO-HYPER.svg",
    name: "Kabuto hyper Form",
    star: 5,
    sound: "/sounds/kabuto_hyper.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/KABUTO-HyperClockUp.svg",
    name: "Kabuto hyper Clockup Form",
    star: 6,
    sound: "/sounds/kabuto_hyperclockup.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/GATACK-MASKED.svg",
    name: "Gatack masked form",
    star: 3,
    sound: "/sounds/gatack.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/GATACK-RIDER.svg",
    name: "Gatack",
    star: 4,
    sound: "/sounds/gatack_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/GATACK-HYPER.svg",
    name: "Gatack hyper Form",
    star: 5,
    sound: "/sounds/gatack_hyper.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/GATACK-HyperClockUp.svg",
    name: "Gatack hyper Clockup Form",
    star: 6,
    sound: "/sounds/gatack_hyperclockup.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/KICK-HOPPER.svg",
    name: "Kick Hopper",
    star: 5,
    sound: "/sounds/kick_hopper.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/PUNCH-HOPPER.svg",
    name: "Punch Hopper",
    star: 5,
    sound: "/sounds/punch_hopper.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/DRAKE-MASKED.svg",
    name: "Drake masked form",
    star: 3,
    sound: "/sounds/gatack.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/DRAKE-RIDER.svg",
    name: "Drake",
    star: 4,
    sound: "/sounds/gatack_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/THEBEE-MASKED.svg",
    name: "TheBee masked form",
    star: 3,
    sound: "/sounds/gatack.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/THEBEE-RIDER.svg",
    name: "TheBee",
    star: 4,
    sound: "/sounds/gatack_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/SASWORD-MASKED.svg",
    name: "Sasword masked form",
    star: 3,
    sound: "/sounds/gatack.mp3",
    type: 2,
  },
  {
    frontPath: "/images/kabuto_front.webp",
    thumbnail: "/characters/kabuto/SASWORD-RIDER.svg",
    name: "Sasword",
    star: 4,
    sound: "/sounds/gatack_rider.mp3",
    type: 2,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KRRy-Ryuki.svg",
    name: "Ryuga",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Ryuki_Survive.svg",
    name: "Ryuga Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/dark_ryuki.svg",
    name: "Dark Ryuga",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_ryuga_survive.svg",
    name: "Dark-Ryuga Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Knight.svg",
    name: "Knight",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Knight_Survive.svg",
    name: "Knight Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Ouja.svg",
    name: "Ouja",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KRRy-Oujasurvive.svg",
    name: "Ouja Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Zolda.svg",
    name: "Zolda",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_zolda_survive.svg",
    name: "Zolda Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Gai.svg",
    name: "Gai",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_gai_survive.svg",
    name: "Gai Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Scissors.svg",
    name: "Scissor",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_scissor_survive.svg",
    name: "Scissor Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Raia.svg",
    name: "Raia",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_raia_survive.svg",
    name: "Raia Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Femme.svg",
    name: "Femme",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_femme_survive.svg",
    name: "Femme Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Imperer.svg",
    name: "Imperer",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_imperer_survive.svg",
    name: "Imperer Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Verde.svg",
    name: "Verde",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_verde_survive.svg",
    name: "Verde Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KR-Tigar.svg",
    name: "Tigar",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_tiger_survive.svg",
    name: "Tigar Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/kamen_rider_odin.svg",
    name: "Odin",
    star: 5,
    sound: "/sounds/ryuki.mp3",
    type: 4,
  },
  {
    frontPath: "/images/ryuki_front.webp",
    thumbnail: "/characters/ryuki/KRRy-Odin.svg",
    name: "Odin Survive",
    star: 6,
    sound: "/sounds/ryuki_survive.mp3",
    type: 4,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku.svg",
    name: "Goku",
    star: 1,
    sound: "/sounds/dragonballz/goku.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj1.svg",
    name: "Goku SSJ1",
    star: 2,
    sound: "/sounds/dragonballz/goku_ssj1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj2.svg",
    name: "Goku SSJ2",
    star: 3,
    sound: "/sounds/dragonballz/goku_ssj2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj3.svg",
    name: "Goku SSJ3",
    star: 4,
    sound: "/sounds/dragonballz/goku_ssj3.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj4.svg",
    name: "Goku SSJ4",
    star: 5,
    sound: "/sounds/dragonballz/goku_ssj4.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj5.svg",
    name: "Goku SSJ God",
    star: 6,
    sound: "/sounds/dragonballz/goku_ssj_god.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gogeta.svg",
    name: "Gogeta",
    star: 5,
    sound: "/sounds/dragonballz/gogeta.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gogeta_v2.svg",
    name: "Gogeta v2",
    star: 6,
    sound: "/sounds/dragonballz/gogeta_v2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegito.svg",
    name: "Vegito",
    star: 6,
    sound: "/sounds/dragonballz/vegito.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/bulma.svg",
    name: "Bulma",
    star: 1,
    sound: "/sounds/dragonballz/bulma.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta.svg",
    name: "Vegeta",
    star: 1,
    sound: "/sounds/dragonballz/vegeta.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/trunks.svg",
    name: "trunks",
    star: 1,
    sound: "/sounds/dragonballz/trunks.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goten.svg",
    name: "goten",
    star: 1,
    sound: "/sounds/dragonballz/goten.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gohan.svg",
    name: "gohan",
    star: 1,
    sound: "/sounds/dragonballz/gohan.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/piccolo.svg",
    name: "piccolo",
    star: 1,
    sound: "/sounds/dragonballz/piccolo.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/chichi.svg",
    name: "chichi",
    star: 1,
    sound: "/sounds/dragonballz/chichi.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_1.svg",
    name: "frieza",
    star: 1,
    sound: "/sounds/dragonballz/frieza.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/broly.svg",
    name: "broly",
    star: 5,
    sound: "/sounds/dragonballz/broly.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_2.svg",
    name: "frieza 2nd form",
    star: 2,
    sound: "/sounds/dragonballz/frieza_2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_3.svg",
    name: "frieza 3rd form",
    star: 3,
    sound: "/sounds/dragonballz/frieza_3.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_super.svg",
    name: "frieza final form",
    star: 4,
    sound: "/sounds/dragonballz/frieza_super.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_mecha.svg",
    name: "mecha frieza",
    star: 5,
    sound: "/sounds/dragonballz/frieza_mecha.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/frieza_golden.svg",
    name: "golden frieza",
    star: 6,
    sound: "/sounds/dragonballz/frieza_golden.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/beerus.svg",
    name: "beerus",
    star: 6,
    sound: "/sounds/dragonballz/beerus.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_kid.svg",
    name: "kid buu",
    star: 3,
    sound: "/sounds/dragonballz/buu_kid.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_good.svg",
    name: "good buu",
    star: 4,
    sound: "/sounds/dragonballz/buu_good.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_evil.svg",
    name: "evil buu",
    star: 4,
    sound: "/sounds/dragonballz/buu_evil.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_super.svg",
    name: "super buu",
    star: 5,
    sound: "/sounds/dragonballz/buu_super.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_tenks.svg",
    name: "buu-tenks",
    star: 6,
    sound: "/sounds/dragonballz/buu_tenks.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_han.svg",
    name: "buu-han",
    star: 6,
    sound: "/sounds/dragonballz/buu_han.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/buu_piccolo.svg",
    name: "buu-piccolo",
    star: 6,
    sound: "/sounds/dragonballz/buu_piccolo.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/cell_jr.svg",
    name: "Cell Jr.",
    star: 3,
    sound: "/sounds/dragonballz/cell_jr.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/cell_1.svg",
    name: "Cell",
    star: 4,
    sound: "/sounds/dragonballz/cell_1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/cell_2.svg",
    name: "Cell 2nd Form",
    star: 5,
    sound: "/sounds/dragonballz/cell_2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/cell_3.svg",
    name: "Cell Final Form",
    star: 6,
    sound: "/sounds/dragonballz/cell_3.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gohan_ssj1.svg",
    name: "Gohan SSJ1",
    star: 2,
    sound: "/sounds/dragonballz/gohan_ssj1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goten_ssj1.svg",
    name: "Goten SSJ1",
    star: 2,
    sound: "/sounds/dragonballz/goten_ssj1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gohan_ssj2.svg",
    name: "Gohan SSJ2",
    star: 3,
    sound: "/sounds/dragonballz/gohan_ssj2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ssj_blue.svg",
    name: "Goku SSJ Blue",
    star: 6,
    sound: "/sounds/dragonballz/goku_ssj_blue.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_ultra_instinct.svg",
    name: "Goku ultra instinct",
    star: 6,
    sound: "/sounds/dragonballz/goku_ultra_instinct.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gotenks.svg",
    name: "Gotenks",
    star: 3,
    sound: "/sounds/dragonballz/gotenks.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/gotenks_ssj3.svg",
    name: "Gotenks SSJ3",
    star: 4,
    sound: "/sounds/dragonballz/gotenks_ssj3.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/trunks_ssj1.svg",
    name: "Trunks SSJ1",
    star: 2,
    sound: "/sounds/dragonballz/trunks_ssj1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/trunks_ssj2.svg",
    name: "Trunks SSJ2",
    star: 3,
    sound: "/sounds/dragonballz/trunks_ssj2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta_ssj1.svg",
    name: "Vegeta SSJ1",
    star: 2,
    sound: "/sounds/dragonballz/vegeta_ssj1.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta_ssj2.svg",
    name: "Vegeta SSJ2",
    star: 3,
    sound: "/sounds/dragonballz/vegeta_ssj2.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta_ssj3.svg",
    name: "Vegeta SSJ3",
    star: 4,
    sound: "/sounds/dragonballz/vegeta_ssj3.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta_ssj4.svg",
    name: "Vegeta SSJ4",
    star: 5,
    sound: "/sounds/dragonballz/vegeta_ssj4.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/vegeta_ssj_blue.svg",
    name: "Vegeta SSJ Blue",
    star: 3,
    sound: "/sounds/dragonballz/vegeta_ssj_blue.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/goku_black.svg",
    name: "Black Goku",
    star: 5,
    sound: "/sounds/dragonballz/goku_black.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/zamasu.svg",
    name: "Zamasu",
    star: 6,
    sound: "/sounds/dragonballz/zamasu.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/great_ape.svg",
    name: "Great Ape",
    star: 6,
    sound: "/sounds/dragonballz/great_ape.mp3",
    type: 6,
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/shenron.svg",
    name: "Shenron",
    star: 7,
    sound: "/sounds/dragonballz/shenron.mp3",
    type: 6,
    video: "/videos/shenron.mp4",
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/porunga.svg",
    name: "porunga",
    star: 7,
    sound: "/sounds/dragonballz/porunga.mp3",
    type: 6,
    video: "/videos/porunga.mp4",
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/dark_shenron.svg",
    name: "dark shenron",
    star: 7,
    sound: "/sounds/dragonballz/dark_shenron.mp3",
    type: 6,
    video: "/videos/dark_shenron.mp4",
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/super_shenron.svg",
    name: "super shenron",
    star: 7,
    sound: "/sounds/dragonballz/super_shenron.mp3",
    type: 6,
    video: "/videos/super_shenron.mp4",
  },
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/ultimate_shenron.svg",
    name: "ultimate shenron",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 6,
    video: "/videos/ultimate_shenron.mp4",
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/shukaku.svg",
    name: "shukaku",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/matatabi.svg",
    name: "matatabi",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/isobu.svg",
    name: "isobu",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/songoku.svg",
    name: "songoku",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/kokuo.svg",
    name: "kokuo",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/raijuu.svg",
    name: "raijuu",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/chomei.svg",
    name: "chomei",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/gyuki.svg",
    name: "gyuki",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/kurama.svg",
    name: "kurama",
    star: 6,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/shinju.svg",
    name: "shinju",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/kaguya.svg",
    name: "kaguya",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/hagoromo.svg",
    name: "hagoromo",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/hamura.svg",
    name: "hamura",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/indra.svg",
    name: "indra",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
  {
    frontPath: "/images/naruto_front.webp",
    thumbnail: "/characters/naruto/ashura.svg",
    name: "ashura",
    star: 7,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 7,
  },
];

export const SPELL_CARDS: ICard[] = [
  {
    frontPath: "/images/dragonballz_front.webp",
    thumbnail: "/characters/dragonballz/ultimate_shenron.svg",
    name: "1 star",
    star: 0,
    sound: "/sounds/dragonballz/ultimate_shenron.mp3",
    type: 6,
  },
];
